### ISSUE TITLE
Jade watch

### ISSUE THREAD

**Issue by dusigner** [CodeShareEducation/firefront-boilerplate#1]
Tentei usar o Boilerplate. 

Porém, quando faço qualquer alteração nos arquivos .jade apos salva-lo o reload limpa toda a pasta .app/ recria o html e esquece de recriar a pasta .assets/

**Comment by WendellAdriel** [comment]
Muito obrigado @dusigner, fiz umas alterações e acho que está ok agora.
Se puder fazer alguns testes e me dar um retorno.

**Comment by dusigner** [comment]
Acredito que aqui na minha maquina alguns fatores foram responsável para o problema. 
Como permissão de usuários para escrever e criar arquivos. Que resolvi rápido acessando como usuário root.

Apos a mudança que você implementou esta perfeito. Valeu!

**Comment by WendellAdriel** [comment]
@dusigner eu que agradeço pela ajuda! :wink:
